name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'dev', 'feature/*' ]
  pull_request:
    branches: [ 'main', 'dev' ]

jobs:
  build-and-test:
    runs-on: windows-latest # Temporary switch to windows till https://github.com/microsoft/vstest/issues/4549 is released in dotnet version after 7.0.400
    env:
      solutionName: Microsoft.Kiota.Serialization.Json.sln
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore -c Release /p:UseSharedCompilation=false
      - name: Test
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
